- type: job
  id: Mime
  name: job-name-mime
  playTimeTracker: JobMime
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 10800
  startingGear: MimeGear
  icon: "Mime"
  supervisors: job-supervisors-hop
  access:
  - Theatre
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: MimePowers

- type: startingGear
  id: MimeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMime
    back: ClothingBackpackMimeFilled
    head: ClothingHeadHatBeret
    belt: ClothingBeltSuspenders
    gloves: ClothingHandsGlovesLatex
    shoes: ClothingShoesColorWhite
    pocket1: CrayonMime
    pocket2: Paper
    mask: ClothingMaskMime
    id: MimePDA
    ears: ClothingHeadsetService
  innerclothingskirt: ClothingUniformJumpskirtMime
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelMimeFilled
